export interface CapsuleMoment {
  id: string;
  timestamp: string; // ISO String
  timecode: string;  // e.g., CAP-2026.06.17-14.51.34
  photoUrl: string;  // base64 image content or fallback design URL
  justification: string;
  audioUrl?: string; // Base64 or Blob storage of the recorded audio intent
  reflection?: string; // AI Reflection generated by Gemini or backup local logic
  tags: string[];
  filter: "raw" | "noire" | "amber" | "clay" | "solstice";
  location?: {
    latitude: number;
    longitude: number;
    description?: string;
  };
}

export interface AppSettings {
  vibrationEnabled: boolean;
  shutterSound: boolean;
  brutalistBorders: boolean;
  filterIntensity: number; // 0 to 100
  aiAssistedTags: boolean;
  defaultFilter: "raw" | "noire" | "amber" | "clay" | "solstice";
}
